### ISSUE TITLE
The runtime library should handle PSQLException internally

### ISSUE THREAD

**Issue by ytr-sakamoto** [opensourcecobol/Open-COBOL-ESQL-4j#15]
When invalid SQL is executed, the runtime library throws PSQLException.
Instead of exposing PSQLException to COBOL programmers, the runtime library should handle the exception internally.

For example, if you try to insert data into a non-existent table, the runtime library will display the following error message.
```
Exception in thread "main" org.postgresql.util.PSQLException: ERROR: relation "emp" does not exist
  Position: 13
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:322)
        at org.postgresql.jdbc.PgPreparedStatement.getParameterMetaData(PgPreparedStatement.java:1666)
        at SQLVar.setParam(SQLVar.scala:30)
        at Operation$$anon$1.$anonfun$apply$7(Operation.scala:132)
        at Operation$$anon$1.$anonfun$apply$7$adapted(Operation.scala:131)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
        at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:889)
        at Operation$$anon$1.apply(Operation.scala:131)
        at Operation$$anon$1.apply(Operation.scala:94)
        at cats.free.Free.$anonfun$foldMap$1(Free.scala:145)
        at cats.package$$anon$1.tailRecM(package.scala:76)
        at cats.free.Free.foldMap(Free.scala:143)
        at cats.free.Free.$anonfun$foldMap$1(Free.scala:146)
        at cats.package$$anon$1.tailRecM(package.scala:76)
        at cats.free.Free.foldMap(Free.scala:143)
        at CobolRunnableWrapper.run(Main.scala:22)
        at CobolRunnableWrapper.run$(Main.scala:16)
        at OCESQLExecParams.run(Main.scala:218)
        at CobolRunnableWrapper.run(Main.scala:13)
        at CobolRunnableWrapper.run$(Main.scala:13)
        at OCESQLExecParams.run(Main.scala:218)
        at f.LABEL_5(f.java:339)
        at f.entryFunc(f.java:591)
        at f.LABEL_2(f.java:142)
        at f.entryFunc(f.java:588)
        at f.f_(f.java:112)
        at f.main(f.java:605)
```

**Comment by ytr-sakamoto** [comment]
I have fixed this issue in 7cf2358c902b318f19bebb978a62cc5876220195
